name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - run: ./gradlew checkstyleMain

      - uses: jwgmeligmeyling/checkstyle-github-action@v1.2
        with:
          path: '**/reports/checkstyle/main.xml'

  spotbugs:
    name: SpotBugs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - run: ./gradlew spotbugsMain

      - uses: jwgmeligmeyling/checkstyle-github-action@v1.2
        with:
          path: '**/reports/spotbugs/main.xml'
