name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    name: "Test & Coverage"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - name: Gradle codeCoverageReport
        run: ./gradlew codeCoverageReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/jacoco/report.xml
